# EDA 2 - Working with the tags

In [1]:
# imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import numbers

In [2]:
# import cleaned dataframe

with open('data/df_cleaned.json', 'r') as f:
  data = json.load(f)

df = pd.DataFrame(data)

# check the data

df

,image_path,tags,uuid,length,price_length,cleaned_price
0,champkoi_data/18f755_A_32_Female_Kohaku_[Nogam...,['Kohaku'],18f755,32.0,7,14000.0
1,gckoi_data/d9a7dbc_HIGH_QUALITY_SAKAI_BLOODLIN...,"['kohaku', 'koi', 'Marukyu', 'nisai']",d9a7dbc,24.0,6,3500.0
2,gckoi_data/88ec869_ISA_KOHAKU_GUARANTEE_FEMALE...,"['isa', 'kohaku', 'koi', 'nisai']",88ec869,21.5,6,2500.0
3,gckoi_data/3a7df4e_DAINICHI_3SAI_FEMALE_KOHAKU...,"['dainichi', 'fall 2024', 'kohaku', 'koi', 'sa...",3a7df4e,27.0,6,3800.0
4,gckoi_data/cb26670_DAINICHI_BLOODLINE_KOHAKU_2...,"['dainichi', 'fall 2024', 'kohaku', 'koi', 'ni...",cb26670,20.0,5,600.0
...,...,...,...,...,...,...
3129,sacramentokoi_data/99a251_Yellow_Dragon_16″_–_...,"[Yellow, Dragon, Aokiya]",99a251,16.0,7,650.0
3130,sacramentokoi_data/e04f2c_Yellow_Dragon_17″_–_...,"[Yellow, Dragon, Aokiya]",e04f2c,17.0,7,600.0
3131,sacramentokoi_data/754a14_Yellow_Ginga_14″_–_2...,"[Yellow, Ginga]",754a14,14.0,7,375.0
3132,sacramentokoi_data/1cb46d_Yellow_Ginga_19″_–_2...,"[Yellow, Ginga]",1cb46d,19.0,9,1600.0
3133,sacramentokoi_data/ba392c_Yellow_Ginga_20″_–_2...,"[Yellow, Ginga]",ba392c,20.0,9,2300.0

In [3]:
# count all instances of all tags

tags_dict = {}

for tag_list in df['tags']:
  if isinstance(tag_list, list):
    for tag in tag_list:
      tags_dict[tag] = tags_dict.get(tag, 0) + 1

tags_dict

{'Gin': 274,
 'Rin': 261,
 'Showa': 179,
 'showa': 1,
 'Karashigoi': 15,
 'Doitsu': 196,
 'Kogane': 6,
 'Ochiba': 46,
 'Benigoi': 41,
 'Ki': 28,
 'Matsuba': 136,
 'Hi': 54,
 'Utsuri': 113,
 'Tancho': 60,
 'Sanke': 234,
 'Goshiki': 37,
 'Shiro': 51,
 'Beni': 69,
 'Kumonryu': 31,
 'Maruten': 14,
 'Hariwake': 304,
 'Jumbo': 2,
 'Kage': 2,
 'Back': 1,
 'Diamond': 4,
 'Kohaku': 258,
 'Kujaku': 301,
 'Red': 2,
 'Chagoi': 43,
 'Asagi': 32,
 'Platinum': 26,
 'Kawarimono': 91,
 'Black': 3,
 'Matsukawabake': 6,
 'Gi': 1,
 'Saragoi': 1,
 'Kin': 22,
 'Cha': 1,
 'Sumi': 3,
 'Goromo': 44,
 'Shusui': 68,
 'Aka': 19,
 'Yamabuki': 60,
 'HI': 1,
 'Kikokuryu': 86,
 'Kigoi': 14,
 'sanke': 2,
 'rin': 1,
 'Copper': 1,
 'Kabuto': 1,
 'Ginrin': 8,
 'Mizuho': 2,
 'Ogan': 2,
 'Hutsuri': 1,
 'Nijikawa': 1,
 'Professional': 1,
 '7MM': 1,
 'Pellet-44': 1,
 'lbs': 1,
 'Aigoromo': 1,
 'Yamato': 33,
 'Nishiki': 37,
 'Butterfly': 133,
 'Penny"': 1,
 'Nezu': 6,
 'Ogon': 95,
 'Soragoi': 23,
 'Lemon': 2,
 'Hikari': 3,
 'Bekko': 80,
 'Muji': 1,
 'Kikusui': 97,
 'Kinsui': 8,
 'Root': 1,
 'Beer': 1,
 'Aragoke': 13,
 'Orenji': 12,
 'Tie"': 1,
 'Shubunkin': 19,
 'Goldfish': 10,
 'Fancy': 2,
 'Tail': 2,
 'Top"': 1,
 'Hesei': 1,
 'RIn': 1,
 'Kikisui': 1,
 'Flower': 1,
 'Heisei': 2,
 'Metallic': 18,
 'Karsugoi': 1,
 'Cream': 1,
 'Hisei': 1,
 'Flannel"': 1,
 'Toro': 2,
 'Asagi and Shusui': 49,
 'Imported Koi': 1582,
 'Koi': 1582,
 'Single Fish': 1871,
 'Single Koi': 1582,
 'Gosanke': 261,
 'All Hikari Koi': 1017,
 'Hikarimoyo': 842,
 'Aka Bekko': 32,
 'Shiro Bekko': 27,
 'Fantail': 28,
 'Goldfish For Sale': 289,
 'Imported Goldfish': 289,
 'Single Goldfish': 289,
 '"Crystal\'s Featured Fish"': 280,
 'Featured Goldfish': 48,
 'Bubble Eye': 12,
 'Ryukin': 48,
 'Butterfly Koi': 795,
 'Hikarimuji': 208,
 'Yamato Nishiki': 85,
 'Heisei Nishik': 29,
 'Kin Kikokuryu': 77,
 'Platinum Ogon': 39,
 'Yamabuk': 15,
 'Ochiba Shigure': 36,
 'Heisei Nishiki': 44,
 'Koromo': 28,
 'Hi Utsuri': 28,
 'Utsurimono': 44,
 'Ki Utsuri': 7,
 'Orenji Ogon': 32,
 'Oranda': 103,
 'Ki Bekko': 7,
 'Gold Crown': 1,
 'Shiro Utsuri': 9,
 'Hajiro': 5,
 'Butterfly Tail': 21,
 'Other Tancho': 1,
 'Wakin': 6,
 'Beni Matsukawabakke': 3,
 'Pearlscale': 19,
 'Ranchu': 37,
 'Matsukawabakke': 2,
 'Sarasa Comet': 6,
 '4-5" Koi & Butterfly Koi': 143,
 'Ai': 4,
 'Albino': 4,
 'Mukashi': 6,
 'Yellow': 15,
 'Ginga': 8,
 'Aokiya': 20,
 'Kaneko': 3,
 'Matsukawabaki': 2,
 'Fukasawa': 2,
 'Ikarashi': 8,
 'Ozumi': 6,
 'Karasu': 2,
 'Toshi': 2,
 'Pearl': 11,
 'Scaled': 1,
 'Zakura': 1,
 'Sakura': 2,
 'Dragon': 9}

In [15]:
# create a dictionary from the tags_dict

tags_df = pd.DataFrame(tags_dict.items(), columns=['tags', 'count'])

tags_df.sort_values(by='count', ascending=False).head(50)

                          tags  count
97                 Single Fish   1871
95                Imported Koi   1582
96                         Koi   1582
98                  Single Koi   1582
100             All Hikari Koi   1017
101                 Hikarimoyo    842
112              Butterfly Koi    795
20                    Hariwake    304
26                      Kujaku    301
107            Single Goldfish    289
106          Imported Goldfish    289
105          Goldfish For Sale    289
108  "Crystal's Featured Fish"    280
0                          Gin    274
1                          Rin    261
99                     Gosanke    261
25                      Kohaku    258
14                       Sanke    234
113                 Hikarimuji    208
5                       Doitsu    196
2                        Showa    179
139   4-5" Koi & Butterfly Koi    143
10                     Matsuba    136
62                   Butterfly    133
12                      Utsuri    113
126                     Oranda    103
71                     Kikusui     97
65                        Ogon     95
31                  Kawarimono     91
44                   Kikokuryu     86
114             Yamato Nishiki     85
69                       Bekko     80
116              Kin Kikokuryu     77
17                        Beni     69
40                      Shusui     68
13                      Tancho     60
42                    Yamabuki     60
11                          Hi     54
16                       Shiro     51
94            Asagi and Shusui     49
109          Featured Goldfish     48
111                     Ryukin     48
7                       Ochiba     46
39                      Goromo     44
123                 Utsurimono     44
120             Heisei Nishiki     44
28                      Chagoi     43
8                      Benigoi     41
117              Platinum Ogon     39
15                     Goshiki     37

1. Kohaku
2. Sanke
3. Hikarimuji
4. Showa
5. Matsuba
6. Utsuri & Utsurimono
7. Ogon & Platinum Ogon
8. Kawarimono
9. Kikokuryu & Kin Kikokuryu
10. Bekko
11. Shusui & Asagi and Shusui
12. Tancho
13. Yamabuki
14. Shiro
15. Goromo
16. Heisei Nishiki
17. Chagoi
18. Benigoi
19. Goshiki

In [16]:
# export tags_df to csv

tags_df.to_csv('data/tags_df.csv', index=False)